# Cargo.toml
[package]
name = "Fuel"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.4"
rand = "0.8"
sha2 = "0.10"
fuel-merkle = "0.50.0"

[[bench]]
name = "bench"
harness = false

[dependencies]
criterion = "0.4"
fuel-merkle = "0.50.0"
hex = "0.4"
sha2 = "0.10"
rand = "0.8"